### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [lukechampine/blake3#10]
Dear Luke,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?
I am eager to try b3sum implemented in Go, because @oconnor663 is in no hurry to [fix Rust’s one][1].

[1]: https://github.com/BLAKE3-team/BLAKE3/issues/78#issuecomment-801425510

**Comment by lukechampine** [comment]
This is just a library, it does not provide a b3sum binary.

I dunno why you're having issues with b3sum but I have great respect for Jack and trust him to do what's right.

**Comment by sergeevabc** [comment]
Thanks, Luke.
Link leads to the report, which is preceded by Jack’s guess on what could be wrong, so he does know, but so far does nothing.
