### ISSUE TITLE
Support newer cpuid

### ISSUE THREAD

**Issue by jgoerzen** [lukechampine/blake3#12]
Hi,

While packaging this for Debian, we have cpuid v2 in the repository and I needed to get it to compile with that version.

The patch for compatibility with cpuid v2 is simple:

```
--- a/cpu.go
+++ b/cpu.go
@@ -5,6 +5,6 @@
 import "github.com/klauspost/cpuid"
 
 var (
-	haveAVX2   = cpuid.CPU.AVX2()
-	haveAVX512 = cpuid.CPU.AVX512F()
+	haveAVX2   = cpuid.CPU.Supports(cpuid.AVX2)
+	haveAVX512 = cpuid.CPU.Supports(cpuid.AVX512F)
 )
```

Thanks!

**Comment by lukechampine** [comment]
fixed in https://github.com/lukechampine/blake3/commit/09d3897aaa0fdbc603afcf54cfe25bf5d677a6b4
