### ISSUE TITLE
could we remove the panic?

### ISSUE THREAD

**Issue by marcosrmendezthd** [lukechampine/blake3#16]
could just return an error

https://github.com/lukechampine/blake3/blob/7afca5966e5e77e5e595d4aba20fa619fe1070e8/blake3.go#L283

**Comment by lukechampine** [comment]
The docstring of `io.Seeker` does not specify how an invalid `whence` should be handled, so implementations naturally differ. Some return an error; others panic; others do nothing (usually leaving `offset = 0`). Personally, I consider this to be a developer error, making it non-recoverable, and therefore panicking seems appropriate.

**Comment by marcosrmendezthd** [comment]
understood
