### ISSUE TITLE
go get fails due to signed shift

### ISSUE THREAD

**Issue by james-antill** [lukechampine/blake3#6]
% go get lukechampine.com/blake3       
    # lukechampine.com/blake3
    ../../../lukechampine.com/blake3/blake3.go:302:16: invalid operation: 1 << i (shift count type int, must be unsigned integer)

**Comment by lukechampine** [comment]
This is a feature that was added in Go 1.13: https://golang.org/doc/go1.13#language

It's not a big deal to change it, but seeing as Go 1.14 is due out this month, I think it's fair to require Go 1.13.
