### ISSUE TITLE
possible for blake3 to have 224 bit version?

### ISSUE THREAD

**Issue by gitmko0** [lukechampine/blake3#7]
possible for blake3 to have 224 bit version?

**Comment by lukechampine** [comment]
It's unusual for modern protocols to use 224-bit hashes, so I don't plan on adding a `Sum224` function to this package, but you can easily implement it yourself:

```go
func Sum224(b []byte) (out [28]byte) {
    h := blake3.New(28, nil)
    h.Write(b)
    h.Sum(out[:0])
    return
}
```
